name: tafsir
description: Tafsir.

publish_to: 'none'

version: 2.2.2+22

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.2.2+1
  flutter_svg: ^0.22.0
  flutter_widget_from_html_core: ^0.6.1+1
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  http: ^0.13.3
  just_audio: ^0.7.5
  provider: ^5.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share: ">=2.0.4"
  shared_preferences: ">=2.0.6"
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.6
  wakelock: ^0.5.2

dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  lint: ^1.5.3

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/go-to-aayah/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: fonts/Scheherazade-Regular.ttf
    - family: KFGQPC-Uthman-Taha-Naskh
      fonts:
        - asset: fonts/KFGQPC-Uthman-Taha-Naskh-Regular.ttf
    - family: me-Quran
      fonts:
        - asset: me-Quran.ttf
    - family: noorehira
      fonts:
        - asset: noorehira-Regular.ttf
    - family: PDMS-Saleem-QuranFont
      fonts:
        - asset: PDMS-Saleem-QuranFont-Regular.ttf
    - family: ShaikhHamdullahMushaf
      fonts:
        - asset: ShaikhHamdullahMushaf.ttf
