name: tafsir
description: Tafsir.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+7

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayer: ^0.8.1
  cached_network_image: ^2.4.1
  flutter_bloc: ^6.1.1
  flutter_cache_manager: ^2.0.0
  flutter_widget_from_html_core: ^0.5.1+4
  google_fonts: ^1.1.1
  http: ^0.12.2
  scrollable_positioned_list: ^0.1.8
  share: '>=0.6.4+3 <2.0.0'
  shared_preferences: '>=0.5.8 <2.0.0'
  sqflite: ^1.3.2+1
  url_launcher: ^5.7.10
  wakelock: ^0.2.1+1

dev_dependencies:
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
